### ISSUE TITLE
There is a person that has no date of birth, did anyone forget to clean that record?

### ISSUE THREAD

**Issue by Xiaohan-Alyssa-Zhang** [Xiaohan-Alyssa-Zhang/CleverCogs-Group7#2]
Since lynda said that any users who don't have date of birth should be deleted. Don't forget to clean this kind of data!

**Comment by MuyuDeng** [comment]
OK, Thanks for the reminder! I'll add it up now!

**Comment by MuyuDeng** [comment]
OK, Thanks for the reminder! I'll add it up now!
