### ISSUE TITLE
What is our data classification based on?

### ISSUE THREAD

**Issue by JuneJuneJie** [Xiaohan-Alyssa-Zhang/CleverCogs-Group7#5]
How did we make the data classification in the categories of "Internet" and "Category"?

**Comment by MuyuDeng** [comment]
I categorized each activity according to its unique characteristics. For example, the new Shopping category including has been added to include all kinds of shopping platforms and shopping brands, and Diet including food types, restaurant names, and takeaway platforms. Thank you for your reminder! I will upload a more detailed and comprehensive breakdown to GitHub.

**Comment by JuneJuneJie** [comment]
Classification basis

1)	Entertainment: all kinds of entertainment.
2)	Health&Care：all activities with 'Health' or 'Care'.
3)	Transportation: both public transportation and private cars.
4)	Help: all unsolved activities, including questions, support, etc.
5)	Game：all kinds of games, including online games, puzzle games, board games, two-player games, etc.
6)	Video: including movies, video sites and individual videos.
7)	Social Network: all kinds of social platforms.
8)	Interest: personal interests.
9)	Location: including address, city and building.
10)	Shopping: all kinds of shopping platform and shopping brand.
11)	Covid-19: all information related to the coronavirus.
12)	Local Information: local information with city name.
13)	Sports: including all types of sports and teams.
14)	Home：including electrical appliances and household items.
15)	Reading: all kinds of books.
16)	Information: nouns and activities with 'information'.
17)	Art: all activities related to art.
18)	Photo: all activities with 'photo'.
19)	Diet: including food type, restaurant, brand and takeaway platform.
20)	Skill: all kinds of skills.
21)	Money: money matter.
22)	Repair: all activities with 'repair'.
23)	News: all kinds of news.
24)	Blackwood: all activities with 'Blackwood'.
25)	Google: all activities with 'Google'
26)	Weather: all activities with 'weather'.
27)	Music: including playlist, single, album, etc.
28)	CleverCogs: all activities with 'CleverCogs'.
29)	Learn: all activities with 'Learn About Me'.
30)	Radio: all kinds of radio.
31)	Family&Friend: way to contact and communicate with family and friends.
32)	Actor&Actress: names of actors and actresses.
33)	Mail: brands of mail.
34)	TV: including TV shows, TV series, etc.
35)	Travel: including travel recommendation, guide, etc.
36)	Document: including instructions and conditions.
37)	History: all activities with 'history'.
38)	Creature: all kinds of animals.
39)	Phone: including 'phone'.
40)	Html Page: activities with a '.com' suffix.
41)	Gallery: all activities with 'gallery'.
